title: "Mit den Augen eines Vaters"
subtitle: "Ein Vater. Ein Sohn. Und die Liebe, die bleibt."
author: "Asterios Raptis"
isbn: ""
edition: "1"
publisher: ""
date: "2025"
language: "de"
description: "Persönliche Erzählung eines Vaters über das Leben mit seinem behinderten Sohn. Eine wahre Geschichte über Liebe, Schmerz, Hoffnung und Würde – erzählt aus der Sicht eines Mannes, der geblieben ist, als alles zerbrach."
keywords: [ ]
cover_image: "assets/covers/cover.png"
output_formats: [ "pdf", "epub", "docx" ]
kdp_enabled: false
